# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a0b02ca8aa0a33ce6e7b1ceb9a2c5bdb1a9b80ce2091ad8eb1eed907b55691930ad2ab123c7dc2cc2e8df6368e71dab3b037c3ec98712628a9b2cdeb5e46b2

test:
  secret_key_base: 3c96a687759b32694de050f77172c93e8f1646e88b88f7364263b40b25a28f0b2bbcd191190b69688ad5ad1b78ac11aa85503863c8dd89a30feb4c4d064fe39d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
